### ISSUE TITLE
Strips of cyan/magenta/yellow in frame 0 of gravity-driven flow example

### ISSUE THREAD

**Issue by joseph-long** [markstock/vic2d#1]
First of all, thanks for making this free and open source (and with documentation)! I was able to compile and run it, but the output of the case I tried doesn't look like I'd expect.

For the example case "Gravity-driven flow in horizontal channel, Re=100k" from the http://markjstock.org/vic2d/ page, `vic2d -x 2048 -y 1152 -px -grav -0.2 1.0 -vd 1e-5 -t -tf run27_1153x2049_bwspread4.png -td 2e-7 -c -cf run27_1153x2049.png -cd 1e-7 -cn 10` produces an odd looking artifact in frame 0:

![out_000000](https://user-images.githubusercontent.com/31168267/58003723-3a1a5c80-7a96-11e9-86c7-9936c32e5ad8.png)

**Comment by markstock** [comment]
Joe, thanks for pointing that out! I must have left a few changes in when I worked on the program for a recent art exhibit. Ah, there it is, `vic2d.c` line 64: just set `use_PARTICLES = FALSE` and you'll be good. I just checked it in.
